// 수록 기준: 1차 출처(책/연설/편지/당대 기록)로 확인된 명언만 등재한다.
// 모든 항목은 original, lang, source, year, sourceUrl을 반드시 포함한다.
// 출처를 제시할 수 없으면 등재하지 않는다. 애매하면 탈락시킨다.
//
// id 규칙: app.js의 즐겨찾기가 id로만 매칭하므로 id는 절대 재사용하지 않는다.
// 삭제된 id: 1,2,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,
//            27,28,29,31,32,33,34,35,36,38,39,40
// 다음 id: 56
//
// 한국어 text는 반드시 original에서 번역한다. 원문의 주장(주어/서술어/한정 조건)을
// 바꾸는 의역은 금지한다.

const QUOTES = [
  {
    id: 3,
    text: "오늘 할 수 있는 일을 내일로 미루지 마라.",
    author: "벤저민 프랭클린",
    original: "Never leave that till tomorrow which you can do today.",
    lang: "en",
    source: "『부자가 되는 길(The Way to Wealth)』 / 가난한 리처드의 달력",
    year: 1758,
    sourceUrl: "https://wist.info/franklin-benjamin/70869/",
  },
  {
    id: 4,
    text: "천 리 길도 발밑 한 걸음에서 시작된다.",
    author: "노자",
    original: "千里之行，始於足下",
    lang: "lzh",
    source: "『도덕경』 제64장",
    year: -400,
    sourceUrl: "https://zh.wikipedia.org/zh-tw/%E5%8D%83%E9%87%8C%E4%B9%8B%E8%A1%8C%E5%A7%8B%E4%BA%8E%E8%B6%B3%E4%B8%8B",
  },
  {
    id: 6,
    text: "위대한 일을 해내는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.",
    author: "스티브 잡스",
    original: "The only way to do great work is to love what you do.",
    lang: "en",
    source: "스탠퍼드대 졸업식 연설 (6월 12일)",
    year: 2005,
    sourceUrl: "https://news.stanford.edu/stories/2005/06/youve-got-find-love-jobs-says",
  },
  {
    id: 21,
    text: "성공한 사람이 되려 하지 말고, 가치 있는 사람이 되려고 하라.",
    author: "알베르트 아인슈타인",
    original: "Try not to become a man of success, but rather try to become a man of value.",
    lang: "en",
    source: "LIFE 「Death of a Genius」 (윌리엄 밀러 기록, 5월 2일자)",
    year: 1955,
    sourceUrl: "https://quoteinvestigator.com/2017/11/20/value/",
  },
  {
    id: 30,
    text: "네가 너 자신을 믿는 순간, 너는 사는 법을 알게 된다.",
    author: "요한 볼프강 폰 괴테",
    original: "Sobald du dir vertraust, sobald weißt du zu leben.",
    lang: "de",
    source: "『파우스트』 1부 2062행 (서재 장면)",
    year: 1808,
    sourceUrl: "https://www.aphorismen.de/zitat/119125",
  },
  {
    id: 37,
    text: "관찰의 영역에서 우연은 오직 준비된 정신만을 돕는다.",
    author: "루이 파스퇴르",
    original: "Dans les champs de l'observation le hasard ne favorise que les esprits préparés.",
    lang: "fr",
    source: "두에 강연 — 릴 대학 이학부 개설 기념 (12월 7일)",
    year: 1854,
    sourceUrl: "https://fr.wikisource.org/wiki/Discours_prononc%C3%A9_%C3%A0_Douai_le_7_d%C3%A9cembre_1854_%C3%A0_l%E2%80%99occasion_de_l%E2%80%99installation_solennelle_de_la_facult%C3%A9_des_lettres_de_Douai_et_de_la_facult%C3%A9_des_sciences_de_Lille",
  },
  {
    id: 41,
    text: "반드시 죽고자 하면 살고, 반드시 살고자 하면 죽는다.",
    author: "이순신",
    original: "必死則生，必生則死",
    lang: "lzh",
    source: "『난중일기』 1597년 9월 15일 (명량해전 전날)",
    year: 1597,
    sourceUrl: "https://ko.wikiquote.org/wiki/%EC%9D%B4%EC%88%9C%EC%8B%A0",
  },
  {
    id: 42,
    text: "하루라도 책을 읽지 않으면 입 안에 가시가 돋는다.",
    author: "안중근",
    original: "一日不讀書口中生荊棘",
    lang: "lzh",
    source: "유묵 (보물 제569-2호), 뤼순 감옥",
    year: 1910,
    sourceUrl: "http://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1121105690200",
  },
  {
    id: 43,
    text: "삼군의 장수는 빼앗을 수 있어도, 한 사람의 뜻은 빼앗을 수 없다.",
    author: "공자",
    original: "三軍可奪帥也，匹夫不可奪志也",
    lang: "lzh",
    source: "『논어』 자한편",
    year: -450,
    sourceUrl: "https://www.zdic.net/hant/%E4%B8%89%E8%BB%8D%E5%8F%AF%E5%A5%AA%E5%B8%A5%EF%BC%8C%E5%8C%B9%E5%A4%AB%E4%B8%8D%E5%8F%AF%E5%A5%AA%E5%BF%97",
  },
  {
    id: 44,
    text: "하늘이 큰 임무를 내리려 할 때는, 먼저 그 마음을 괴롭게 하고 몸을 지치게 한다.",
    author: "맹자",
    original: "天將降大任於是人也，必先苦其心志，勞其筋骨",
    lang: "lzh",
    source: "『맹자』 고자하",
    year: -300,
    sourceUrl: "https://ctext.org/mengzi/gaozi-ii",
  },
  {
    id: 45,
    text: "본래 땅 위에 길은 없었다. 걷는 사람이 많아지면 그것이 곧 길이 된다.",
    author: "루쉰",
    original: "其實地上本沒有路；走的人多了，也便成了路",
    lang: "zh",
    source: "단편소설 「고향(故鄕)」, 『신청년』 제9권 제1호",
    year: 1921,
    sourceUrl: "https://zh.wikisource.org/zh-hant/%E6%95%85%E9%84%89",
  },
  {
    id: 46,
    text: "어려워서 감히 못하는 것이 아니라, 감히 하지 않기에 어려워지는 것이다.",
    author: "세네카",
    original: "Non quia difficilia sunt non audemus, sed quia non audemus difficilia sunt.",
    lang: "la",
    source: "『도덕서한(Epistulae Morales)』 104편 26절",
    year: 65,
    sourceUrl: "https://www.loebclassics.com/view/seneca_younger-epistles/1917/pb_LCL077.205.xml",
  },
  {
    id: 47,
    text: "꿈을 향해 당당히 나아가며 그리던 삶을 살고자 하면, 예기치 못한 성공을 만난다.",
    author: "헨리 데이비드 소로",
    original: "If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.",
    lang: "en",
    source: "『월든』 결론장",
    year: 1854,
    sourceUrl: "https://etc.usf.edu/lit2go/90/walden-or-life-in-the-woods/1698/conclusion/",
  },
  {
    id: 48,
    text: "세상은 고통으로 가득하지만, 그 고통을 이겨내는 일로도 가득하다.",
    author: "헬렌 켈러",
    original: "Although the world is full of suffering, it is full also of the overcoming of it.",
    lang: "en",
    source: "에세이 『낙관론(Optimism)』",
    year: 1903,
    sourceUrl: "https://www.gutenberg.org/files/31622/31622-h/31622-h.htm",
  },
  {
    id: 49,
    text: "사람은 이미 이룬 것은 보지 못하고, 아직 남은 일만 보게 된다.",
    author: "마리 퀴리",
    original: "One never notices what has been done; one can only see what remains to be done.",
    lang: "en",
    source: "동생 요제프에게 보낸 편지 (3월 18일) / 『피에르 퀴리』 1장(1923) 수록",
    year: 1894,
    sourceUrl: "https://en.wikiquote.org/wiki/Marie_Curie",
  },
  {
    id: 50,
    text: "내 성공의 비결은 이것이다. 나는 어떤 변명도 하지 않았고, 받아주지도 않았다.",
    author: "플로렌스 나이팅게일",
    original: "I attribute my success to this:—I never gave or took any excuse.",
    lang: "en",
    source: "본햄 카터에게 보낸 편지 / E. 쿡 『The Life of Florence Nightingale』(1913) 1권 506쪽 수록",
    year: 1861,
    sourceUrl: "https://quoteinvestigator.com/2016/07/30/excuse/",
  },
  {
    id: 51,
    text: "「너는 화가가 아니다」라는 목소리가 들리거든 기어이 그려라. 그러면 그 목소리는 잠잠해진다.",
    author: "빈센트 반 고흐",
    original: "If you hear a voice within you saying: You are no painter, then paint by all means, lad, and that voice will be silenced, but only by working.",
    lang: "nl",
    source: "동생 테오에게 보낸 편지 (10월, 드렌터)",
    year: 1883,
    sourceUrl: "https://quoteinvestigator.com/2026/06/24/voice-paint/",
  },
  {
    id: 52,
    text: "나는 운명의 목덜미를 움켜쥘 것이다. 운명이 나를 완전히 굴복시키지는 못한다.",
    author: "루트비히 판 베토벤",
    original: "Ich will dem Schicksal in den Rachen greifen, ganz niederbeugen soll es mich gewiß nicht.",
    lang: "de",
    source: "베겔러에게 보낸 편지, 빈 (11월 16일)",
    year: 1801,
    sourceUrl: "https://www.beethoven.de/en/g/schicksal",
  },
  {
    id: 53,
    text: "투쟁이 없으면 진보도 없다.",
    author: "프레더릭 더글러스",
    original: "If there is no struggle there is no progress.",
    lang: "en",
    source: "서인도 해방 기념 연설, 커낸다이과 (8월 3일)",
    year: 1857,
    sourceUrl: "https://www.gilderlehrman.org/ap-african-american-studies/unit-2/organizing-for-freedom/west-india-emancipation-1857",
  },
  {
    id: 54,
    text: "굴복하지 마라. 절대로, 절대로, 절대로 굴복하지 마라.",
    author: "윈스턴 처칠",
    original: "Never give in, never give in, never, never, never.",
    lang: "en",
    source: "해로 스쿨 연설 (10월 29일)",
    year: 1941,
    sourceUrl: "https://winstonchurchill.org/resources/speeches/1941-1945-war-leader/never-give-in/",
  },
  {
    id: 55,
    text: "천재는 1퍼센트의 영감과 99퍼센트의 땀으로 이루어진다.",
    author: "토머스 에디슨",
    original: "Genius is one per cent inspiration, ninety-nine per cent perspiration.",
    lang: "en",
    source: "Harper's Monthly 인터뷰 (본인이 1927년 편지로 저작을 확인)",
    year: 1932,
    sourceUrl: "https://en.wikiquote.org/wiki/Thomas_Edison",
  },
];
